name: Main CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '$'
          AWS_SECRET_ACCESS_KEY: '$'
        run:
          aws s3 cp --recursive --region ap-northeast-2 dist s3://duckgugong.shop